services:
  api:
    build: .
    restart: unless-stopped
    
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "127.0.0.1:8000:8000"
    # command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:?DATABASE_USERNAME is required}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?DATABASE_PASSWORD is required}
      POSTGRES_DB: ${DATABASE_NAME:?DATABASE_NAME is required}
    
    volumes:
      - postgres-db:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
volumes:
  postgres-db:
