"""create total_price column

Revision ID: 0d92ea04a598
Revises: 8f1f812f5685
Create Date: 2026-07-24 20:37:07.558133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d92ea04a598'
down_revision: Union[str, Sequence[str], None] = '8f1f812f5685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serviceticket', sa.Column('total_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serviceticket', 'total_price')
    # ### end Alembic commands ###
