"""init alembic and create tables

Revision ID: e027a4cefba5
Revises: 
Create Date: 2026-07-25 13:52:00.958881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e027a4cefba5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carwash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manager_code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employee_code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paymenttype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('carwash_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carwash_id'], ['carwash.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('carwash_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carwash_id'], ['carwash.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'EMPLOYEE', name='staffrole'), nullable=False),
    sa.Column('carwash_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carwash_id'], ['carwash.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicletype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('carwash_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carwash_id'], ['carwash.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serviceticket',
    sa.Column('license_plate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('car_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('employee_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('carwash_id', sa.Integer(), nullable=False),
    sa.Column('created_by_staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carwash_id'], ['carwash.id'], ),
    sa.ForeignKeyConstraint(['created_by_staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serviceticket_scheduled_at'), 'serviceticket', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serviceticket_scheduled_at'), table_name='serviceticket')
    op.drop_table('serviceticket')
    op.drop_table('vehicletype')
    op.drop_table('staff')
    op.drop_table('service')
    op.drop_table('paymenttype')
    op.drop_table('carwash')
    op.drop_table('owner')
    # ### end Alembic commands ###
